version: "3"
services:
  phpcontainer:
    image: marcelocorrea/desafio-docker-php
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s php-fpm
    restart: always
    depends_on: 
     - mysql
    networks:
     - backend
     - frontend 
  nginx:
    image: marcelocorrea/desafio-docker-nginx
    restart: always
    ports:
     - 8000:80
    depends_on:
     - phpcontainer
    networks:
     - frontend
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

